### Get all motos
GET http://localhost:3000/housing-location
Accept: application/json



### Create a new moto
POST http://localhost:3000/housing-location
Content-Type: application/json

{
    "name": "IES Comercio",
    "city": "Logroño",
    "state": "La Rioja",
    "photo": "https://img.desmotivaciones.es/201201/desmotivaciones430.jpg",
    "availableUnits": 3,
    "wifi": true,
    "laundry": true
}
